import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Montserrat} from 'next/font/google'

 
const Mont = Montserrat({
  weight: ['200', '300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#f9f9f9] ${Mont.className}`} >
        <Navbar/> {children} <Footer/>
        </body>
        
    </html>
  )
}
